on:
  push:
    branches:
      - prod
      - dev

jobs:
  deploy-prod:
    if: github.ref == 'refs/heads/prod'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
      - name: HubSpot Deploy Action
        uses: HubSpot/hubspot-cms-deploy-action@v1.7
        with:
          src_dir: .
          dest_dir: shalom_world_web_theme
          portal_id: ${{ secrets.hubspot_portal_id }}
          personal_access_key: ${{ secrets.hubspot_personal_access_key }}

  deploy-dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
      - name: HubSpot Deploy Action
        uses: HubSpot/hubspot-cms-deploy-action@v1.7
        with:
          src_dir: .
          dest_dir: shalom_world_web_theme
          portal_id: ${{ secrets.hubspot_portal_id_dev }}
          personal_access_key: ${{ secrets.hubspot_personal_access_key_dev }}
